### ISSUE TITLE
Kafka python API_VERSION confusion

### ISSUE THREAD

**Issue by neoeahit** [dpkp/kafka-python#1042]
I am  bit confused with the API_VERSION.
We are in the process of migrating to kafka 10. We have pinned the API_VERSION in kafka_python to 0.9. Now running against kafka 10 it all works fine. I was expecting this to break. Does it imply API_VERSION 0.9 is compatible with kafka10?

Also what benefits does one get in that case to change API_VERSION to 0.10 from 0.9?

Also kafka 0.10.2 is out, are there plans to support it? ( ref: https://github.com/dpkp/kafka-python/blob/65ba8822b10e6f8a3ba4e9a6b0a1e6f9b785c18e/kafka/client_async.py#L162)

**Comment by dpkp** [comment]
the kafka protocol generally is backwards compatible such that newer kafka broker versions will still accept and respond to older kafka clients that use older protocol versions. If you set an api_version directly, you are telling the kafka-python client to always send api requests using that version. This should work for all broker versions equal to or newer than the client version you have chosen. In this case, `api_version=(0, 9)` should work for any 0.9+ kafka broker.

In my opinion, the biggest protocol difference between 0.10 and 0.9 is that the message format changed slightly to include a timestamp (also LZ4 should actually work).

Otherwise you might take a look at MetadataRequest v1 , FetchRequest v2 and v3, ProduceRequest v2, and ApiVersionRequest v0 at https://kafka.apache.org/protocol

**Comment by neoeahit** [comment]
Thanks @dpkp for the quick response.

I am curious do we have to do anything as per https://kafka.apache.org/documentation/ "Upgrading from 0.8.x, 0.9.x, 0.10.0.x or 0.10.1.x to 0.10.2.0"
which mentions 
"_If log.message.format.version is still lower than 0.10.0 at this point, wait until all consumers have been upgraded to 0.10.0 or later, then change log.message.format.version to 0.10.2 on each broker and restart them one by one._"

I am not sure if I need to upgrade anything on the consumer side/client side using kafka-python.

I just tested using log.message.format.version to 0.10.2 on kafka broker side and kafka-python pinned to 0.9, and things seem to work. So I can safely conclude the above point is more towards java consumers and kafka-python will work just fine?  Please correct me incase I am wrong.

**Comment by dpkp** [comment]
Yes, you should follow that advice. Though note that you do not strictly have to follow those instructions to upgrade -- they are actually recommendations for best cluster performance. Old clients will still work with new brokers that have upgraded log.message.format.version . But doing so does put more strain on the brokers, particularly when dealing with compressed messagesets.

**Comment by neoeahit** [comment]
Thanks @dpkp for the help!
