### ISSUE TITLE
Tooling to manually reset a consumers offset and commit it

### ISSUE THREAD

**Issue by infecto** [dpkp/kafka-python#1106]
What I want to do: Stop a running consumer group. Run a custom tool that manually commits the offset for aforementioned consumer group. Start consumer group and it picks up at new offset.

1) Is this possible?
2) If so does anyone have any guidance on how it can be accomplished within kafka-python. I realize we have the given methods that should work but I cannot seem to properly commit these changes to kafka. I can seek to beginning and manually run poll and it starts at the beginning but I want seek_to_beginning to commit this offset to kafka.

**Comment by jeffwidman** [comment]
If you restart an old consumer group, by default it will pick up from the currently stored offsets. So yes, this should work fine. 

For manually committing the offsets, there's a new CLI tool coming out with the upcoming Kafka 0.11 that will make this much much easier. Otherwise you'll need to just call `committed()` with explicit offsets to store the commits.
