### ISSUE TITLE
Better way to detect consumer bootstrap failure when calling poll?

### ISSUE THREAD

**Issue by Ormod** [dpkp/kafka-python#1136]
I'm wondering how should the client behave if bootstrapping fails for a KafkaConsumer.

Since a failing bootstrap does not raise an exception, if you just blindly start calling poll after init, the poll call will hang forever trying to connect. 

So what I'm getting at is that at least my current method of doing this is a bit cumbersome and I was wondering if it could be made more convenient somehow.

a) Would it be ok for polling to raise an exception when _bootstrap_fails > 0 since otherwise it will never exit.
or
b) for polling to automatically call consumer._client._bootstrap() again 

Currently what I'm doing is that at initialization time I have a while loop that looks something like: 

(pseudocode)
consumer = KafkaConsumer(hosts)
while True:
    if consumer._client._bootstrap_fails > 0:
       consumer._client._bootstrap(collect_hosts(hosts))
   elif consumer._client._boostrap_fails == 0:
       break

Which is a bit tedious.

**Comment by dpkp** [comment]
We try to follow the official Java client fesign fairly closely. Do you
know how they handle this issue?

**Comment by jeffwidman** [comment]
This doesn't make sense to me, if bootstrap totally fails, you'll get a `kafka.errors.NoBrokersAvailable: NoBrokersAvailable` error.

Closing for now, if I overlooked something, feel free to leave more details.

**Comment by dpkp** [comment]
But `NoBrokersAvailable` is raised from the version probing, not the bootstrap process itself. It is true that we enable version probing by default, but if you configure an explicit `api_version` then you would not get this exception and you would just have a non-functional consumer. Perhaps this is what @Ormod is seeing?

But if this does occur then `consumer.poll` should not hang indefinitely. It should still respect the timeout_ms parameter. So I'm still a little confused about the underlying issue.

Stepping back, however, when bootstrapping does fail it is because either (1) the nodes configured for bootstrapping are down temporarily -- a cluster failure, or maintenance, etc. In these cases the error likely requires manual intervention at the broker, but should not require any changes at the consumer. So we (kafka client) can just carry on with periodic retries until the nodes come back and we can start working again. This is the current behavior. But (2) if the client is just misconfigured -- either the hosts dont exist, or dns is wrong, or some networking issue prevents a connection -- then there is no future recovery without manual intervention on the client side. In this case users would probably benefit from a fast failure. But how to tell the difference between 1 and 2 ? I'm not sure there is any way to do that. Maybe we could add an option that would change the working assumption that all bootstrap errors are broker issues (no exception raised) to assume that all bootstrap errors are client errors (always raise exception).

**Comment by dpkp** [comment]
Closing in favor of sticking with current approach, which assumes that bootstrap data is correct and failures are temporary. As I understand it, this is the same policy used by the java client.
