### ISSUE TITLE
Is subscription by pattern foolproof?

### ISSUE THREAD

**Issue by smontanaro** [dpkp/kafka-python#1195]
I have a couple processes publishing to related topics which differ only in their suffix. One process gathers messages from several of these topics and writes them to files based on their suffix. So, I might have topics like "tribble-pdf", "tribble-txt", "tribble-html", etc. These suffixes are dynamic. I don't know ahead of time what all of them will be, so it's very convenient that the one consumer can subscribe to a pattern.

I'm doing my own committing and use the group_id and value_deserializer kwd args. I have a simple hello world type script. If I replace:

consumer.subscribe(pattern="^tribble")

with

consumer.subscribe(topics=("tribble-pdf", "tribble-xml"))

it works, but of course my subscription doesn't respond to new tribble-* topics. My constructor looks like this:

consumer = kafka.KafkaConsumer(bootstrap_servers="..."
    value_deserializer=json.loads,
    enable_auto_commit=False,
    group_id="tribbles-everywhere")

Anything wrong with that combination of constructor parameters? When it hangs, it never gets a message from the broker.

(BTW, I feel real weird asking for help in what amounts to a bug reporting system. Is this really the right place for these sorts of questions?)

**Comment by smontanaro** [comment]
I will add that it seems most of the time subscribing by pattern doesn't work, but when it does, it latches onto content within a couple seconds. When it fails, I can wait for a mintur or two before giving up and killing the listener. (I'm watching my producer's log file and see it sending plenty of messages.) Almost like there's a race condition somewhere. Also, peeking in the code, I noticed that it uses re.match, so my "^" anchor wasn't necessary. Removing it had no effect.

**Comment by jeffwidman** [comment]
If the topic was not initially present when the consumer first started up, then you have to wait for the consumer to next do a metadata refresh before it will realize there's new topics. This is because the kafka protocol (by design) doesn't support the broker pushing an awareness of new topics. See the docs for `metadata_max_age_ms`, which defaults to every 5 minutes.

For questions like these where you are seeing unexpected behavior that is likely a bug, I am personally fine with you posting here. If it's a usage question where it is likely not a bug, then StackOverflow has a specific tag for `kafka-python` questions. I don't always remember to check that tag, so if you get no traction on it, feel free to post an issue here with a link to the question
