### ISSUE TITLE
list kafka consumer groups class

### ISSUE THREAD

**Issue by luciangutu** [dpkp/kafka-python#1314]
Hi.
Any plans to implement a Kafka consumer groups list class as /opt/kafka/bin/kafka-consumer-groups.sh does? Thanks.

**Comment by jeffwidman** [comment]
This would likely fall under #935

**Comment by luciangutu** [comment]
You might take a look at this one:
https://github.com/amoma-com/zabbix-kafka-consumers-monitor

**Comment by ChristineTChen** [comment]
@jeffwidman is the [`list()`](https://github.com/amoma-com/zabbix-kafka-consumers-monitor/blob/1f9e66897faf078502f8e012762b60682c0cec6d/kafka_consumer_groups.py#L42) function in the zabbix-kafka-consumers-monitor repo the current best way to get a list of consumer groups?

**Comment by jeffwidman** [comment]
@ChristineTChen all you need to do is pass the `ListGroupsRequest_v0` to each broker (because each broker only knows about groups that it manages). This is essentially what the zabbix one does, although they wrapped it with some additional request/retry logic that may or may not be needed depending on the use case.
