### ISSUE TITLE
wo must use consumer.topics(), after use other function?

### ISSUE THREAD

**Issue by zhangtaoa** [dpkp/kafka-python#1321]
First Demo：
from kafka import KafkaConsumer
consumer = KafkaConsumer('test',bootstrap_servers=['172.21.10.136:9092'])
print consumer.assignment()

result:
set([])

The result is empty set

Second Demo：
from kafka import KafkaConsumer
consumer = KafkaConsumer('test',bootstrap_servers=['172.21.10.136:9092'])
print consumer.topics()
print consumer.assignment()

result:
set([u'test', u'test0'])
set([TopicPartition(topic='test', partition=0)])

The result is OK!

so wo must use consumer.topics() ,  after use consumer.assignment()   ;

i  test on windonws !!!

**Comment by dpkp** [comment]
When you pass a topic name to the KafkaConsumer constructor, `KafkaConsumer('test', ...)`, you are using dynamic partition assignment and there is no guarantee that any partitions are assigned (if there are other consumers in the group) or when they will be assigned (depends on rebalance and network operations).

If you want strict control over partition assignment, try `consumer.assign([...])`

**Comment by jeffwidman** [comment]
Also, I haven't double-checked, but IIRC, when you instantiate the consumer it doesn't actually start a dynamic partition  assignment... the first time you trigger something like poll() it will actually go do the initial rebalance. I know it currently works this way for pattern subscriptions because the partition isn't actually assigned until the consumer has done an initial metadata fetch. Although there may be a kafka jira ticket about this to remove the double-metadata fetch... I don't recall exact details, but suffice it to say for your use case you probably will find that if you call `poll()` and then `assignment()` you will have actual partitions assigned.

**Comment by zhangtaoa** [comment]
@jeffwidman  Thanks，I  know，I have tested; 
from kafka import KafkaConsumer
import time

consumer = KafkaConsumer(bootstrap_servers=['172.21.10.136:9092'])
consumer.subscribe(topics=('test','test0'))
while True:
    msg = consumer.poll(timeout_ms=5)
    print msg
    time.sleep(1)
    print consumer.assignment()
