### ISSUE TITLE
Performant Way to run many consumers from a single process

### ISSUE THREAD

**Issue by infecto** [dpkp/kafka-python#1349]
Within our development environment we are attempting to create a performant "catchall" consumer to run all of our consumer code within a single process. Unfortunately we have enough consumers 30+ that is causes a significant enough load on the CPU. 99% of these workers have no traffic across their topics and I was expecting that this would mean little to no CPU overhead.

Has anyone encountered this problem and found any useful patterns to achieve this without significant CPU usage?

I have profiled the code and one of the things i have noticed is numerous calls/cpu ticks to the metrics system and was curious if this might be a potential use of overhead from workers without any traffic. Perhaps there is a sensible way to trim down the usage since in development there is little to no use for measurements?

**Comment by dpkp** [comment]
I'm not sure I understand precisely the configuration you are going for, but generally I recommend using multiprocessing when you need to run many consumers in parallel from the same "process".

It is known that kafka-python is currently CPU-bound at scale (which is why I suggest adding CPUs via multiprocessing), but the metrics system is not a component that I have found to be a large contributor. My benchmarks suggest that the network pipe remains the limiting reagent, including serialization / deserialization and socket handling. But this may change as you add more and more topics. I generally benchmark for performance with consumers that are assigned smallish numbers of topic-partitions (~10).
