### ISSUE TITLE
python <= 2.7.3: TypeError: unpack_from() argument 1 must be string or read-only buffer, not memoryview

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#1378]
This appears to only happen on early versions of python 2.7 -- prior to the 2.7.4 release
```
  File "venv/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 453, in _unpack_message_set
    batch = records.next_batch()
  File "venv/local/lib/python2.7/site-packages/kafka/record/memory_records.py", line 103, in next_batch
    magic, = struct.unpack_from(">b", next_slice, _magic_offset)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not memoryview
```

To support the early versions of python 2.7, we may need to do something like this:
https://github.com/google/flatbuffers/pull/2098

**Comment by dpkp** [comment]
@jeffwidman @tvoinarovskyi thoughts?

**Comment by jeffwidman** [comment]
The attached link says prior to the 2.7.5 release. 2.7.5 was released in May 2013, so it's nearly 5 years old at this point. Thankfully, CentOS 7 shipped with 2.7.5.

Personally, I vote drop support for Python < 2.7.5. Anyone who is on that old of python version can use `kafka-python` 1.3.x. Most of the features available in 1.4 require newer brokers, and folks who are using newer brokers are generally working in environments that allow upgrading to python >= 2.7.5.

I'd rather see our very limited dev time go toward the future rather than supporting a past that is already 5 years old at this point.

**Comment by dpkp** [comment]
It's fixed in 2.7.4. Here is the python bug report: https://bugs.python.org/issue10212 . Unfortunately I have a lot of code at work that is still running on Debian 7 with the system python, which is python 2.7.3..

**Comment by jeffwidman** [comment]
Nothing like reality to shatter dreams. 😃 If you want to fix it, go for it.

LTS for Debian 7 ends May 2018... are you not being forced to upgrade for security reasons?

**Comment by tvoinarovskyi** [comment]
@dpkp the fix does not require use of buffer protocol. But either we test it on older python or we will break it again somewhere in the future

**Comment by zeebonk** [comment]
Hey everyone, I just want to let you know that we've run into this issue in our production setup after upgrading to the latest version of kafka-python. Fortunately it only concerns a single machine which was already eligible for upgrade (Debian 7), so we're going to take that path.

**Comment by tvoinarovskyi** [comment]
We probably should just state the version needed in docs and add a more human readable error for such a case.

**Comment by anmcn** [comment]
We use a commercial product internally that uses Python 2.7.2 - updating Python isn't an option. I've downgraded to kafka-python 1.3.5 for now and that seems to be working.

**Comment by dpkp** [comment]
Closing - wontfix.
