### ISSUE TITLE
Kafka Message Headers support

### ISSUE THREAD

**Issue by Gsantomaggio** [dpkp/kafka-python#1502]
Looking the [documentation](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html#kafka.KafkaProducer.send) seems that it is not possible to add custom headers to the message ( unless I am missing something ).

This is an example how to that in Java:
https://memorynotfound.com/spring-kafka-adding-custom-header-kafka-message-example/ 

Is it a missing feature? 
Thanks

**Comment by dpkp** [comment]
Yes, kafka-python does not support 0.11+ message headers currently. It is a relatively new feature on the server-side, and I haven't had a need for it personally. However, I'm open for consulting / contracting if it is something you feel is important and would like someone to work on adding it. 

Otherwise, I'm happy to review PRs for this!

**Comment by mapapa** [comment]
Hi, are there any immediate plans implementing message headers in python? Many thnaks

**Comment by dpkp** [comment]
Yes, see PR #1574

**Comment by vlcek** [comment]
Hi, I see the PR #1574 as merged. Do I understand corretly this issue is solved, ie the support for message headers is implemented in 1.4.x?

**Comment by jeffwidman** [comment]
Yes!
