### ISSUE TITLE
How to create and delete topic on kafka server?

### ISSUE THREAD

**Issue by girishsv1986** [dpkp/kafka-python#1503]
Hi there,
I want to create and delete topic from kafka server based on some conditions. I have written a simple script just to verify topic creation and deletion using kafka-python admin.py

Issue I'm facing is - at some times script just works fine(with error_code-0 which is success) and at some times it returns 41 which says - NOT_CONTROLLER as per this doc - http://kafka.apache.org/0101/protocol.html#protocol_error_codes

Above issue is causing my functionality to break intermittently.
attached is the script
[kafka_python_test.zip](https://github.com/dpkp/kafka-python/files/2023397/kafka_python_test.zip)

Running the script multiple times, re-produces issue intermittently.
Can someone help me to figure out where it's going wrong?

Also, is there a better way create and delete topics than what I have done

Thanks in Advance.

**Comment by jeffwidman** [comment]
This isn't a kafka-python bug. You will need to handle the error as the state of the cluster changed (the controller moved). So you'll need to find the new controller in order to tell it that you want to create/delete partitions. If you have further questions, since this is a more general kafka question separate from the client library, you might get better answers at StackOverflow or the Kafka mailing list.
