### ISSUE TITLE
Correlation IDs do not match: kafka python offset commit issues

### ISSUE THREAD

**Issue by charankooram** [dpkp/kafka-python#1586]
I am using kafka python for my stream and consistently run into this issue on trying to commit offsets
using the commit_async api. The log below is caught on the error call back function. Could someone please point me to the proper way to triage this issue.

2018-06-21 15:05:46,285 ERROR 112:kafka_qa_ingestion.py(6145) - Exception happened committing offset - CorrelationIdError: : Correlation IDs do not match: sent 4792, recv 4791

I was hoping this would resolve itself since it looked like a low level thing. But after a while the producer just crashes and i'd love any help to figure this out.

Kafka python version: 1.3.5
Kafka version : 0.11

**Comment by charankooram** [comment]
""" code snippets and code configurations """
```
self.consumer = 
KafkaConsumer(
self.topic, 
group_id=consumer_grp_name, 
bootstrap_servers=[source], 
auto_offset_reset="earliest", 
enable_auto_commit=False, 
max_in_flight_requests_per_connection= 16000, 
max_poll_records=500
)
```
```
self.producer = 
KafkaProducer(
bootstrap_servers=[destination], 
max_in_flight_requests_per_connection=16000
)
```
```
def on_send_success(record_metadata, topic_partition, offset_and_meta_data):
            def on_success_offset_commit(args):
                self.logger.debug("Offset successfully committed - {}".format(args))
            def on_err_offset_commit(ex):
                self.logger.error("Exception happened committing offset - {}".format(ex))
            self.logger.debug("{},{},{}".format(record_metadata.topic, record_metadata.partition, record_metadata.offset))
            self.consumer.commit_async(offsets={topic_partition: offset_and_meta_data}).add_callback(
                 on_success_offset_commit).add_errback(on_err_offet_commit)

def on_send_error(excp):
            self.logger.error("Exception happened sending messages to destination kafka broker", exc_info=excp)
            self._send_alert(excp)
```

```
self.producer.send(topic=self.topic, value=record.value).add_errback(on_send_error).add_callback(on_send_success, topic_partition=topic_partition, offset_and_meta_data=OffsetAndMetadata(offset=record.offset, metadata=record.offset))
```

**Comment by charankooram** [comment]
can someone please address this issue and please point me to a way to resolve this. I notice that my code is often breaking due to this and i am not confident to move to production until this resolves or i move to someother streaming library.

**Comment by dpkp** [comment]
The error means that the send and receive messages are out of sync. At the lowest level, every message a client sends to a kafka broker has a "correlation id" embedded in it. Usually this is just an int that increases +1 for each request. When the broker responds to the request, it puts the request correlation id into the response. This let's the client know which response goes with which request.

Here, your error is saying that you were looking for a response to request 4792 but saw instead the prior response for 4791.

The best advice I have for you is to upgrade to the latest release (currently 1.4.4). The protocol layer and correlation id code were updated substantially in 1.4. So even if we could come up with a reason for your error, we probably wouldn't be able to fix it because we've moved on to a different implementation already.
