### ISSUE TITLE
KafkaConsumer of Release 1.4.4 is still very slow

### ISSUE THREAD

**Issue by gzliudan** [dpkp/kafka-python#1659]
I tested Release 1.4.4 just now, the speed problem is not disapper. I use kafka-console-producer.sh to send 2 messages, the KafkaConsumer use more than 3 minutes receive this messages.

#1597

**Comment by tvoinarovskyi** [comment]
Maybe you forget to call ``consumer.close()`` after usage. This seems like a broker issue, like when the consumer has to fail by timeout. Any snippet to reproduce?

**Comment by gzliudan** [comment]
I did not call consumer.close() according to example. My code is as like below:

from kafka import KafkaConsumer
consumer = KafkaConsumer('my_favorite_topic', group_id='my_favorite_group')
for msg in consumer:
     print (msg)

By the way, if I switch to https://github.com/confluentinc/confluent-kafka-python, the confluent's consumer speed is normal. This seems not brokers' problem.

**Comment by dpkp** [comment]
consumer.close() could be the issue if you have short-lived consumers. If you do not call consumer.close() then the broker will keep the rebalance open (stopping all other consumers) for the duration of the session timeout. This is because the broker does not know whether the consumer is still alive or not. Try calling `consumer.close()` at the end of your script and see if that doesn't fix your problem.

**Comment by feiyangzhang** [comment]
I got the same problem. The console's consumer is normal, but release 1.4.4 is very slow.

**Comment by dpkp** [comment]
If you do not call consumer.close() you will not be able to rejoin the same
group id until session times out. Either call close() or use a new group id.

**Comment by dpkp** [comment]
I'm going to assume that you are not calling consumer.close() in your script. The console consumer closes itself -- if you want similar performance, you must do the same. The kafka-python driver, like the java driver, does not attempt to auto-close consumers.

**Comment by dpkp** [comment]
To more fully explain: the reason why closing a consumer is so important is because your consumer group is stateful. If you attempt to join a pre-existing group where prior consumers have not left, the broker will wait for the full session timeout before kicking the old consumer and allowing a new rebalance to complete. This initial "join-group" delay is the most common source of perceived consumer slowness during testing. To avoid it you should close your consumers at the end of your test scripts (including if you kill via sigterm, sighup, sigkill, etc). Alternatively, configure your test script use a different group_id on each attempt.
