### ISSUE TITLE
Kafka Producer sending message: message production rate is higher than the throughput

### ISSUE THREAD

**Issue by Atusshi** [dpkp/kafka-python#1668]
I use the camera to create the image and send to the broker with the wireless link.

I want to create the message for every 0.2 sec. I send messages directly to the broker with the sync mode and timeout for the 1 second and acks = 1. But I notice that I need to send 1message with 1 to 2 seconds because of the wireless link. So I change the timeout to 3 sec. I need to wait for the acks reply from the broker to send a new message.

However, I still want to create the message for every 0.2 and send over the low throughput wireless link. So I rather want to send the multiple messages with only one ack reply from the broker ( like send 5 messages and reply only for the 1st message). I notice that Kafka producer can be set 0, 1, and all for the acks reply.

So How I can set the acks reply from the broker? Do I need to change from the sync mode to async or acks = 1 to acks = 0?

**Comment by jeffwidman** [comment]
Are you using the new `KafkaProducer`?

**Comment by Atusshi** [comment]
# Asynchronous by default
future = producer.send('my-topic', b'raw_bytes')

# Block for 'synchronous' sends
record_metadata = future.get(timeout=10)


just like the usage for the kafka-python.

**Comment by Atusshi** [comment]
![picture1](https://user-images.githubusercontent.com/31284054/50825743-61d11980-136c-11e9-989e-5e1323991131.png)
I only need to make sure about the red message reach to the broker and only want to wait for the black message sending time that is 0.8 sec because each message is support to send every 0.2 sec

**Comment by tvoinarovskyi** [comment]
I feel like there is a misunderstanding here on what an ack is for Kafka. What you actually described is to have your 5 messages to be batched togather and sent as a single request. That way you will get only 1 ack per 5 messages.
To do that you need to use asynchronous send as described above (ie. not wait for future right away) and perform flush every 5 messages.
The problem here is that I fail to understand your business requirement. Do you want every image to be delivered or some images can be dropped if you can't send them fast enough?

**Comment by Atusshi** [comment]
Sorry for my bad explaining.

For me, the network is not reliable and the throughput is low for streaming.

But I still want to send images. 

In this case, if the first image of the image sequence has successfully arrived at the broker, I assume all the images in that sequence has arrived. If not I assume the broker or the link between the broker and the camera has the failure. So the will change the broker to send the images. 

To use as a batched message is one of the solutions. However, to have a real-time is also important for me. So that I cannot use the batched message way.

**Comment by tvoinarovskyi** [comment]
Ok, now I understand the use case in more detail. So you want to rely on the internal TCP layer for delivery guarantee and want to only do a round trip once every 5 images to lower latency. Sadly I can't say that Kafka's protocol is a good fit for the job, I would advise you to build your own RPC on the low connection part and just have a server that pushes that to Kafka over a good connection. But maybe we can get something out of it.

By design the protocol is an RPC, meaning that every Request has a paired Response passed over the socket. Moreover, those are not async by order, every Request will have a paired Response in the same order. If messages are not batched together they will only be sent in parallel if sent over different sockets, defeating the purpose. (There is 1 exception, the ``ask=0`` ProduceRequest does not have a paired response, but lets ignore that one for now, maybe we can get around without it).

But the protocol supports **pipelining**, meaning we can push up to X requests without waiting for the response. While the broker will  process those separately and will still send 5 replies we will not wait for those to get
back to us. Additionaly you can force to have 1 batch per message by putting a low max_batch_size config (say max_batch_size=1), it will let you always add the first message no matter the limit.

So something like this should solve your use case:

```python
producer = KafkaProducer(
    bootstrap_servers=HOSTS,
    acks=1,  # We want that ack
    linger_ms=0,  # We are sending 1 image per batch
    batch_size=1,  # Force 1 message per batch
    retries=0,
    # This one's the key, we pipeline up to 5 requests, set it to 6 just in
    # case we also request Metadata
    max_in_flight_requests_per_connection=6,
)

fut1 = producer.send(topic, FIRST_MESSAGE, partition=0)
fut2 = producer.send(topic, SECOND_MESSAGE, partition=0)
fut3 = producer.send(topic, THIRD_MESSAGE, partition=0)
fut4 = producer.send(topic, FORTH_MESSAGE, partition=0)
fut5 = producer.send(topic, FIFTH_MESSAGE, partition=0)
producer.flush(timeout=0.5)
```

Just do understand what will happen.
First delivery of the image does not mean it was successfully written to Kafka. We disabled retries, so you should check for errors on futures and decide what to do for yourself.
Second, we still have ACK on the protocol level, but that is just another few bytes send on the network. Depending on how TCP handles that it may not even have a difference over 1 ACK you desire. The benefit here is that you will be able to get the result of every produce and handle errors.
Third, it will only work if the requests are sent over the same connection. Sending to the same partition is the easiest way to force that.

**Comment by Atusshi** [comment]
Thank you for your suggestion. I will try in this way.
