### ISSUE TITLE
'module' object has no attribute 'epoll'

### ISSUE THREAD

**Issue by meikuwu** [dpkp/kafka-python#1700]
When I use the thread to initialize KafkaProduce and KafkaConsumer in the gevent application, I am getting the following error ('module' object has no attribute 'epoll').
 If I use patch_all(select=False), then this error goes away,but I need the thread to use it

**Comment by meikuwu** [comment]
pykafka

**Comment by jeffwidman** [comment]
I got bit by this myself a while back... `gevent` and `epoll` don't play nice together. 

You need to set a different `selector` in your `KafkaProducer`/`KafkaConsumer`, I use `kafka.client_async.selectors.PollSelector`...

**Comment by carsonip** [comment]
The default poll impl is checked in global during import, as shown in https://github.com/dpkp/kafka-python/blob/master/kafka/vendor/selectors34.py#L628
Since gevent does not support epoll, please make sure you run gevent monkey patch early enough in your application, such that when you import selectors34.py, epoll is not available and will fallback to poll safely.
