### ISSUE TITLE
Looking for implementation examples

### ISSUE THREAD

**Issue by ncernek** [dpkp/kafka-python#1828]
Hi,

I'm curious if anyone in the community has examples of built-out examples with multiple producers and consumers used at a more complex level.

Thanks.

**Comment by nathanmkaya** [comment]
I'm looking for the same thing as an option instead of using Faust

**Comment by jeffwidman** [comment]
These are actually somewhat rare... for a producer, you typically only need one per cluster, as you can produce to multiple topics using the same producer.

For a consumer, since the typical usage of the `poll()` loop requires heartbeating in every so often, having multiple consumers using `subscribe()` is difficult. It almost forces you to manually use `assign()` if you want to manage multiple consumers simultaneously. Instead, a more typical pattern is to have a single consumer subscribing to multiple topics, and then doing the actual handling of the separate topics _after_ the messages are fetched/consumed.

Can you describe your use case more?

**Comment by tvoinarovskyi** [comment]
Well, we do some more complex stuff using compacted topics, but all of those are not easy to put into an example, requires a lot of tests, etc. We were instead considering using Faust to lower the complexity of the solution. If you share more details on what exactly are you looking for, it's possible to get some example done.
