### ISSUE TITLE
KafkaClient partitions_for_topic returns None even when initialized with topic

### ISSUE THREAD

**Issue by ferozed** [dpkp/kafka-python#1873]
This is the code snippet that I have...

```
        self.kafka_client = KafkaConsumer(self.topic, **kafka_config)
        stream_shards = self.kafka_client.partitions_for_topic(self.topic)
```

I am expecting `stream_shards` to contain the partitions for the topic. But it is `None`.

however, if I call `self.kafka_client.topics()` and then call `partitions_for_topic` it returns correct partitions.

**Comment by georgepsarakis** [comment]
`KafkaConsumer.partitions_for_topic` seem as a read-only method, just retrieves data from the protected variable: 

https://github.com/dpkp/kafka-python/blob/ea35fdfe1d66eb481e3406ad161a1255573dd50f/kafka/cluster.py#L106

In order to populate the topics and partitions metadata, `.update_metadata` needs to run:

https://github.com/dpkp/kafka-python/blob/ea35fdfe1d66eb481e3406ad161a1255573dd50f/kafka/cluster.py#L229

which is called by:

https://github.com/dpkp/kafka-python/blob/79dd508b14fd2d66a8b6d32353e8e64989c4ff84/kafka/client_async.py#L807

and finally:

https://github.com/dpkp/kafka-python/blob/79dd508b14fd2d66a8b6d32353e8e64989c4ff84/kafka/client_async.py#L579

So as far as I understand, a single call to to the server is required in order to populate the internal metadata cache, which is used by `partitions_for_topic`.

I think the solution could be to modify `partitions_for_topic` to also make a call to `.topics` if `ClusterMetadata._partitions` is empty.

**Comment by brouberol** [comment]
@georgepsarakis Thanks for the detailed walk-through! I confirm that calling `kafka_consumer.topics()` before calling `kafka_consumer.partitions_for_topics(..)` "fixes" that issue, which looks like a regression.

**Comment by georgepsarakis** [comment]
Actually, I was wrong in my initial analysis, `KafkaConsumer.partitions_for_topic()` does update topic metadata in a blocking manner (which also happens when calling `topics()`:

https://github.com/dpkp/kafka-python/blob/ea35fdfe1d66eb481e3406ad161a1255573dd50f/kafka/consumer/group.py#L596

@brouberol @ferozed I cannot reproduce it with current master. What Python/Kafka version are you using?

**Comment by georgepsarakis** [comment]
I confirmed that this was indeed the case with release 1.4.6 (latest on PyPI), but works correctly in current master.

I think these changes apply the fix: https://github.com/dpkp/kafka-python/compare/1.4.6...master#diff-9da855eb60eed8ecc72ce217c25e576cL581

**Comment by brouberol** [comment]
Indeed, it appears 1f73287 fixed it. Would you consider releasing a patch version to PyPI? The issue itself is fixed but as long as the patch isn't released, users will still be affected.

Thanks!

**Comment by Baisang** [comment]
Ah, this actually requires both https://github.com/dpkp/kafka-python/commit/1f73287e890a4c68f240dcc8b6966de1e62b65cc and https://github.com/dpkp/kafka-python/commit/1a0f2973190e2bb60909bfcd28e5ad8e732e918e (I made a typo in the first commit, lol)

You can cherry-pick both to a fork for now, I think the maintainers intend to release it in 1.4.7 though
