### ISSUE TITLE
1.4.7

### ISSUE THREAD

**Issue by ofek** [dpkp/kafka-python#1903]
@dpkp Hello there! Are there any blockers for releasing `1.4.7`? If so, can I help?

**Comment by dpkp** [comment]
There are two things on my mind: (1) consumer performance degradation in
#1888 . I have attempted to fix w
https://github.com/dpkp/kafka-python/pull/1902 but it is a significant
internal change and so has risk. I haven't decided whether to make this the
default and allow opt out or make it opt in and wait for a 1.5 release to
make it the default.

(2) Heartbeat thread coordination / deadlocks / timeouts remain an issue.
One structural change that I have deferred is in #1821 . I am undecided
whether to make this change now or in the future after thinking more about
the deadlock issue I mention in the comments.

(3) I would like to make some changes to the network write IO so that we
use non blocking socket send() with a buffer and also improve error
handling. I have done some work on this already but haven't put up a PR.


If you'd like to pitch in, maybe just give me your thoughts on these
issues. How would you manage them?

**Comment by dpkp** [comment]
Also I need to learn to count to three.

**Comment by ofek** [comment]
@dpkp Thanks for the thoughtful response!

1. I'm very sensitive to performance regressions in general, though since it's been a few releases now, I would merge your fix as-is and change the default in a minor release.
2. I'd wait for a minor release.
3. I think that's a good idea but not a blocker for this release.

However, you should know I'm biased for 2 reasons:

1. We're actively waiting to merge PRs that depend on functionality that will be introduced in `1.4.7` 😄 
2. As a fellow maintainer of OSS in my free time, my personal approach is to release incrementally, as often as possible.

**Comment by ofek** [comment]
What do you think?

**Comment by iAnomaly** [comment]
Thanks for pushing on this @ofek. I've also tried to get @jeffwidman and @dpkp to cut a patch release to include my PR #1883 as it resolves handshake failures for unknown root CAs such as Amazon's that are blocking downstream projects such as [Datadog's Kafka consumer integration](https://github.com/DataDog/integrations-core/blob/master/kafka_consumer/requirements.in).

**Comment by ofek** [comment]
@dpkp Any progress on this?

**Comment by dpkp** [comment]
Hi team - I'll take a stab this weekend!

**Comment by ofek** [comment]
@dpkp Great, thanks!

**Comment by dpkp** [comment]
1.4.7 released + uploaded to pypi. Please report any issues!

**Comment by ofek** [comment]
@dpkp Thank you so much!

**Comment by jeffwidman** [comment]
Thanks for all your hard work on this @dpkp!
