### ISSUE TITLE
Unable to send messages when consumer and producer are on different servers

### ISSUE THREAD

**Issue by vatodorov** [dpkp/kafka-python#1917]
Hello,

I can't seem to figure out how to send messages when the producer and the consumer are on different servers. The producer uses the Python package, but I start the consumer using Kafka's shell scripts. If the consumer and producer are on the same VM, I can send messages across successfully, but not when they are on different VMs. Both VMs are in the same network and there is a route between them.

Any help is greatly appreciated. Thanks!

The consumer runs on 10.13.0.107. This VM has the base Kafka installation from here the official distro https://kafka.apache.org/quickstart

    # Start Zookeeper and Kafka and consume messages
    > KAFKA_HOST=10.13.0.107
    > PORT=9092
    > KAFKA_TOPIC="testTopic"
    > cd /opt/kafka_2.12-2.3.0/bin
    > ./zookeeper-server-start.sh ../config/zookeeper.properties
    > ./kafka-server-start.sh ../config/server.properties
    > ./kafka-console-consumer.sh --bootstrap-server $KAFKA_HOST:$PORT --topic $KAFKA_TOPIC --from-beginning

The producer runs in Python on 10.13.0.109

    import json
    import random
    from kafka import KafkaProducer

    kafka_topic = 'testTopic'
    kafka_host = '10.13.0.107'
    kafka_port = '9092'
    kafka_host = '{}:{}'.format(kafka_host, kafka_port)
    
    producer = KafkaProducer(bootstrap_servers=[kafka_host],
                         api_version=(0, 10, 1),
                         ssl_check_hostname=False)
    
    #### Generate a random IP address
    def rand(lb=1, ub=255):
        return random.randrange(lb, ub)
    
    #### Send messages to the consumer
    for i in range(20):
        
        #### Generate sample data
        ip = '{}.{}.{}.{}'.format(rand(), rand(), rand(), rand())
        ioc = {
            'indicator': ip,
            'adversaries': 'BadGuy',
            'attributes': {
                'ThreatLevel': 'High'
            }
        }
    
        print print 'Sending {}'.format(ioc)
    
        #### Send the data to the Kafka consumer
        data = json.dumps(ioc)
        producer.send(kafka_topic, data)

**Comment by rohitsingh23july1986** [comment]
I m facing same problem
Subject : data sending problem from one machine to another machine using Kafka python

Dear ,

We are facing problem when we send one topic data from one machine to another (Kafka server) ,
Actually my requirement is create topic in one machine send this topic via Kafka producer in another Kafka server


When we create topic and send this topic on same machine then we are able to subscribe this topic on same machine


But as per my requirement when we send this topic from one machine to another Kafka server then we are not able to subscribe this topic and when we try to send this topic then only topic name is showing in lenses GUI tool,but inside this topic no data is comming

Please provide me dummy code. In Kafka python  and other file setting which is required for solving this problem


We are suffering this problem since from last week
We also take help from Kafka forum
But are not successful to solve this problem 




Please help to solve this problem
And send one dummy code in python Kafka and other setting which is required to solve this problem

We are using CentOS operating system

Please help me

**Comment by rohitsingh23july1986** [comment]
Dear all,
Any solution for this problem?

**Comment by dpkp** [comment]
This seems like a networking issue. You might try checking the logs and/or enabling debug.
