### ISSUE TITLE
KafkaConsumer  class doesn't work with security_protocol as a SASL_PLAINTEXT 

### ISSUE THREAD

**Issue by fedotarte** [dpkp/kafka-python#1935]
if you create a KafkaConsumer with SASL auth parameters like that:
```
            consumer = KafkaConsumer(bootstrap_servers=str_broker_host,
                                security_protocol='SASL_PLAINTEXT',
                                sasl_mechanism='PLAIN',
                                sasl_plain_username='user',
                                sasl_plain_password='password')
```
it won't work with error Errors.NoBrokersAvailable()

i need it to get topic sizes:
```
# topic name and partition
end_offset = consumer.end_offsets([TopicPartition(topic[0], 0)])
```

Also i checked the class KafkaConsumer, and there is no value  "SASL_PLAINTEXT" for security_protocol.

How can i get the topic size for 0 partition without calling the KafkaConsumer?

Thank you in advance.

**Comment by jeffwidman** [comment]
> Also i checked the class KafkaConsumer, and there is no value "SASL_PLAINTEXT" for security_protocol.

I think this was merely a docs issue that was fixed in https://github.com/dpkp/kafka-python/pull/1921/files but the underlying code should work in 1.4.7. I don't have an environment to test, so if you're seeing problems, a stacktrace would be helpful.

> it won't work with error Errors.NoBrokersAvailable()

Hmm... assuming the above is unrelated, then this is likely indicative of bad configuration param. Can you successfully telnet to the box or run a Java console consumer to verify you have the right connection config params?

> How can i get the topic size for 0 partition without calling the KafkaConsumer?

You can directly do this via `KafkaClient` if needed, but it would require some lower-level work.

**Comment by romulo-dbts** [comment]
I don't know if it helps, but I have been running with the following options without any issues:
```
security_protocol='SASL_SSL'
sasl_mechanism='PLAIN'
sasl_plain_username='user'
sasl_plain_password='password'
```
kafka-python==1.4.7

**Comment by dpkp** [comment]
I'm not aware of a bug in SASL_PLAINTEXT. Please check your user/password and your broker configuration. When in doubt, enable debug logs and take a look at kafka.conn log statements for more insights.
