### ISSUE TITLE
how to use partition_assignment_strategy?

### ISSUE THREAD

**Issue by venthur** [dpkp/kafka-python#1936]
Hi,

the `Consumer` supports as configuration the `partition_assignment_strategy`, which defaults [according to the documentation](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer) to a list of two objects: `[RangePartitionAssignor, RoundRobinPartitionAssignor]`? I don't get how this works, will the consumer chose one of them randomly? What is the correct way to chose i.e. specifically the `RoundRobinPartitionAssignor` -- if i have a list of topics distributed over 3 partitions and I want to utilize more than 3 processes to consume as fast as possible?

Thanks, for the great library and your work!

**Comment by jeffwidman** [comment]
This is probably a better fit for StackOverflow than here, since it's a question about a general kafka consumer configuration param. 

That said, here's a quick summary:
The full list is what that particular consumer supports. The order is the consumer's preference.

When a consumer group starts up, all consumers submit their strategy lists, and the group leader will identify the list of strategies supported by all consumers and pick one from that. This allows you to keep a consumer group online while slowly doing a rolling upgrade until all consumers support the new strategy.

The one part I don't remember is if all consumers support multiple strategies, but the leader has one preference order and all the others have a different preference order, which one gets picked... I suspect the leader's preference order is used, but you'd need to check the code.

As far as which strategy is best for your particular scenario, each one has strengths/weaknesses. I suggest you hit google for "kafka partition assignment strategy" which turns up a few helpful blog posts... you'll also want to read KIP-54 which explains drawbacks with each strategy and suggests an alternative (#1122).

**Comment by venthur** [comment]
I think the question is valid, bc as far as I see upstream supports only one Assignor as argument, but here you give a list of different Assignors. That seems a deviation from upstream and probably needs clarification.
