### ISSUE TITLE
Frequent rebalance of Consumer group when using kafka-python 1.4.6 and 1.4.7

### ISSUE THREAD

**Issue by naoshadmehta** [dpkp/kafka-python#1939]
We're seeing this problem with 1.4.6 and 1.4.7. We have 3 broker nodes and 6 consumers per node. Our topic has 18 partitions and for about an hour or so, we see no issues. After an hour or so, we start seeing:

server.log:[2019-10-29 01:28:16,927] INFO [GroupCoordinator 1]: Preparing to rebalance group tasks_group in state PreparingRebalance with old generation 9 (__consumer_offsets-17) (reason: removing member kafka-python-1.4.7-52039bb5-17c5-42d7-8af3-d95f0dbc3f3f on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)

A few seconds later, we see a new consumer being added:
server.log:[2019-10-29 01:29:00,612] INFO [GroupCoordinator 1]: Preparing to rebalance group tasks_group in state PreparingRebalance with old generation 10 (__consumer_offsets-17) (reason: Adding new member kafka-python-1.4.7-27f5bbac-b1e6-41a9-999b-abb56868e9e2) (kafka.coordinator.group.GroupCoordinator)

After the system gets into this state, we keep seeing remove and add of new members to the consumer group and in a few hours, it reaches a point where the rebalance takes more than 10 minutes to complete. By this time, the lag on the partitions is so high that its impossible to recover from this situation.

Our broker config:
max.session.timeout.ms: 30000
heartbeat.interval.ms: 10000

Consumer config:
max.session.timeout.ms: 10000
heartbeat.interval.ms: 3000
consumer_timeout_ms: 2000

Everything else is left as default.

Any suggestions on what we could tweak in the broker or consumer configs to avoid seeing this issue? I came across this other issue - https://github.com/dpkp/kafka-python/issues/1418 which has been closed after a fix was committed to 1.4.7 but we still see the problem with 1.4.7.

**Comment by dpkp** [comment]
Do you have any logs or metrics from the kafka-python consumers (it looks like these logs are from the broker)?

**Comment by dpkp** [comment]
Regarding specific configurations -- you could try increasing the `session_timeout_ms` in your consumer config to the maximum allowed by your brokers. But this may just paper over the issue. Would be great to get more insight into what is actually happening with your consumers. Do you have a memory leak?

**Comment by jeffwidman** [comment]
nudge @naoshadmehta

**Comment by flatcon** [comment]
I'm seeing very similar issues, though it starts as soon as I start up the service and never stops.  There are almost 100 topics, and it appears to be rebalancing them constantly.  It has made my environment completely unusable.

An example is below:
INFO [GroupCoordinator 0]: Preparing to rebalance group connect-sink-mariadb-FCDB.MSTCUSTOMER_v1 with old generation 12 (__consumer_offsets-17) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Stabilized group connect-sink-test-mariadb-FCUBS.ACTB_HISTORY_v1 generation 13 (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Stabilized group connect-sink-mariadb-FCUBS.STTM_DEBIT_CARD_PRODUCT_v1 generation 27 (__consumer_offsets-1) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Stabilized group connect-sink-mariadb-dbo.cheques generation 29 (__consumer_offsets-1) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Assignment received from leader for group connect-sink-mariadb-FCUBS.STTM_DEBIT_CARD_PRODUCT_v1 for generation 27 (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Preparing to rebalance group connect-sink-mariadb-TEST-FCUBS.CSTB_CONTRACT_v1 with old generation 9 (__consumer_offsets-13) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Assignment received from leader for group connect-sink-mariadb-dbo.cheques for generation 29 (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Assignment received from leader for group connect-sink-test-mariadb-FCUBS.ACTB_HISTORY_v1 for generation 13 (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Stabilized group connect-sink-mariadb-FCUBS.ICTM_ACC_v1 generation 364 (__consumer_offsets-24) (kafka.coordinator.group.GroupCoordinator)
INFO [GroupCoordinator 0]: Assignment received from leader for group connect-sink-mariadb-FCUBS.ICTM_ACC_v1 for generation 364 (kafka.coordinator.group.GroupCoordinator)

It's going to be a struggle for me to debug or find config info, as I took over this mature kafka project without any prior knowledge, due to staff turnover.  Any help would be great!

**Comment by jeffwidman** [comment]
Please open a new ticket, and include your kafka-python version and broker version.

From the logs, this kinda looks like Kafka Connect libraries btw, which is unrelated to this library.

**Comment by cbernardone** [comment]
Was this ever resolved? We're having the same issue. We're still on 1.4.7. Will upgrading to latest version correct?

**Comment by holuborhee** [comment]
@cbernardone and to everyone else who may be having this issue, I just resolved mine after 2 months of the issue recurring. My fix was to optimize my system, [this answer on SO](https://stackoverflow.com/a/59394095/2236388) recommended that too. The first 4 to 5 articles of [this series](https://chrzaszcz.dev/2019/05/26/kafka-101/) gave me a good foundation on the inner workings of Kafka.
