### ISSUE TITLE
Rebalancing not occurring

### ISSUE THREAD

**Issue by karthikmurugadoss** [dpkp/kafka-python#1942]
Great work on the library and documentation!

I'm having a bit of difficulty understanding when rebalancing should and should not occur. In particular my use case is as follows:
- One topic with two partitions
- Initially one consumer (a second consumer joins at a later point of time)
- The producer sends 20 messages (Round robin partitioning) to the topic
- The consumers take 1 minute to process each message

As soon as I send the 20 messages (10 to each partition), the single consumer as expected begins to process them. However, at this point (while consumer 1 is busy processing), if I introduce consumer 2, I had expected a rebalance to occur and the two partitions to be split - one for each consumer. 

However, the rebalance does not occur right away. The kafka logs show the following line
```
Preparing to rebalance group 1 in state PreparingRebalance with old generation 44 (__consumer_offsets-49) (reason: Adding new member kafka-python-1.4.7-95992b00-ff44-42bc-86a1-6374657b5bc9
```
I see the log message for consumer 1 `Heartbeat failed for group 1 because it is rebalancing` and this keeps repeating until eventually `Heartbeat poll expired, leaving group`. If the consumer did not expire (by reducing processing time for each message or reducing the number of message), then the rebalance occurs only after all of the 20 messages are processed by consumer 1 (that is, consumer 2 had been idle all this time). 

Any insight on the above would be very helpful! Am I missing something basic? (is 1 minute a very long processing time? Is rebalancing supposed to happen only when all or majority of consumers are "idle"?)

**Comment by dpkp** [comment]
I suspect the issue here is that, while you are probably using the kafka consumer iterator interface, you are still processing records in batches, which is the default as of 1.4.7. Rebalancing/committing/etc will only happen in between batches, so even though the broker is signaling a rebalance, and the consumer's heartbeat thread is signaling a rebalance, the consumer iterator itself will not honor that rebalance until you are done processing the batch. The default batch size is 500 records. Try adjusting `max_poll_records` => 1 . With such a high per-message processing time, you may also want to adjust your `max_poll_interval_ms`, which defaults to 5 minutes and sets the maximum amount of time allowed between "batches" (overflowing this timeout will cause the heartbeat thread to assume the consumer has failed and will attempt to leave the group automatically).
