### ISSUE TITLE
Performance of assign(), seek(), poll()

### ISSUE THREAD

**Issue by zhengl7** [dpkp/kafka-python#1949]
Not really a bug but hope to get some explanation on some performance issues seen with random access using `seek(partition, offset)`.

The Kafka has a single topic, 10 nodes, less than 100 partitions, message rate about 1.5k/sec. Has a few regular streaming consumer groups that simply subscribe to the topic, and one special consumer group.

The special consumer group doesn't simply subscribe to the topic and poll, but instead, listens to a message queue for a Kafka message's `partition` and `offset`, and then in turn grab the message from Kafka by calling the basically the following sequence

```python
consumer.assign([partition])
consumer.seek(partition, offset)
consumer.poll(1, timeout)
```
The offsets in the queue are all of messages recently written into Kafka.

Here is where things get interesting for this special consumer, 

1. If only put a subset of Kafka messges' offset in the queue, let's say 1% or less, then the poll call has pretty noticeable timeout rates, that it couldn't get message for even 1 second, while success polls are less than 5ms.

2. But, if we put all the Kafka's messages offsets in the message queue, meaning every single Kafka message will be obtained once using its offset by this client, the timeout is almost completely gone! 

3. Seems that if the message queue has delays, meaning the consumer only gets offsets of not the most recent Kafka messages (offsets a few thousands earlier than the latest), then the outgoing traffic from Kafka increased tremendously. If the ad-hoc polls are mostly on most recent messages, then nothing too abnormal.  

This led me to guess that the client is actually getting more messages back from Kafka behind the scene even if the caller only calls `poll(1)`, and has some kind of smart caching. I tried to read the source a little bit but still couldn't connect the full circle. Hopefully someone with deeper knowledge can provide some insights.  

kafka-python version: 1.4.6
broker version: 2.2.0
client flags: enable_auto_commit=False

**Comment by dpkp** [comment]
Kafka is tuned for linear scans, not key-value lookups, so it doesn't surprise me that your approach is causing some timeouts. You might be better off having whatever system is pushing partition/offsets to a kafka topic also push the message values to a true k/v store, perhaps redis or dynamodb.

Nonetheless, you are correct that poll(1) does not affect the number of records fetched, only the records returned. The full batch of messages is cached internally so that linear reads for the "next message" are fast. The purpose of max_records=1 is actually to solve the problem where long-processing consumers cause heartbeat or session timeouts. It was not designed to power k/v lookups.

But if you really want to dig in more, take a look at the batch configurations:
```
fetch_min_bytes
fetch_max_wait_ms
fetch_max_bytes
max_partition_fetch_bytes
```
