### ISSUE TITLE
simple consumer: WARN: Fetch size too small 

### ISSUE THREAD

**Issue by Captcool** [dpkp/kafka-python#1950]
I use simple consumer to consume messages of __consumer_offsets topic to get the lags.
when I upgrade the kafka server to 2.2 , the log was all of the warn message:
2019-11-10 17:29:57,533 WARNING simple.py _fetch-432 line Fetch size too small, increase to 8388608 (2x) and retry

and follow is the consumer parameter

        consumer = SimpleConsumer(kafka_handler, 'lag_monitor', '__consumer_offsets', auto_commit=False,
                partitions=[ID], buffer_size=MAX_FETCH_BUFFER_SIZE_BYTES, max_buffer_size=1024 * 1024 * 2) 

and the MAX_FETCH_BUFFER_SIZE_BYTES is 8*4096

in the old 1.0 kafka server it worked well but in kafka server 2.2 it not worked

the warn :
![image](https://user-images.githubusercontent.com/14876126/68541979-8f9a4b00-03e1-11ea-8995-432512bda0f6.png)

the consumer parameter:
![image](https://user-images.githubusercontent.com/14876126/68541989-accf1980-03e1-11ea-94dc-3bedfe39ee91.png)

why the warning will appear

**Comment by dpkp** [comment]
Please note that we deprecated SimpleConsumer some time ago and have recently removed it entirely from kafka-python. You should switch to KafkaConsumer as soon as possible.

For what it is worth, this warning is likely caused by a different encoding of messages on this topic in the newer kafka brokers. Is consumer this topic directly supported? I would expect that message formats are likely to change without warning from broker version to broker version.
