### ISSUE TITLE
async KafkaConsumer

### ISSUE THREAD

**Issue by scientistnik** [dpkp/kafka-python#1964]
```python
from kafka import KafkaConsumer

consumer = KafkaConsumer('my_favorite_topic')
for msg in consumer:
        print (msg)
```
is there any way to receive messages asynchronously?

I didn’t think of anything better then:
```python
while True:
   await asyncio.sleep(0.01)
   messages = consumer.poll()
   #  parse messages
```

**Comment by RaviTezu** [comment]
@scientistnik Did you get it working in any other way ? I am looking for a way to consume limited number of messages and not running an infinite loop.

**Comment by dpkp** [comment]
I'm not exactly sure what concurrency model you're looking for.... But if you are using asyncio, you might take a look at https://github.com/aio-libs/aiokafka , which shares some internals with kafka-python. Otherwise, you can use consumer.poll with a timeout and manage processing / scheduling however you like. That said, a more common approach is just to use a separate process for your consumers. Or, if you are up for it, in-process threads.

**Comment by RaviTezu** [comment]
[Just for people coming here]
I was able to get my requirement met by setting `enable_auto_commit` to `True` and a timeout on the consumer using `consumer_timeout_ms`.
