### ISSUE TITLE
Get event time stamp in consumer

### ISSUE THREAD

**Issue by jyotisachdeva57** [dpkp/kafka-python#2102]
I am using kafka-python==2.0.1

producer.py

   def queue(self, key, value):
        self.producer.send(
            MESSAGES_TOPIC,
            timestamp_ms=int(time.mktime(datetime.utcnow().timetuple())),
            key=key,
            value=value,
        )

In timestamp_ms, I am adding the time at which the message gets queued.
In consumer, I am using:

`json.loads(event.body.decode('utf-8'))`

How can i get timestamp_ms value in consumer?

**Comment by jeffwidman** [comment]
I don't recall for sure, but I have a hunch it's part of the consumer message/record metadata... meaning it's not going to be part of the `event.body` at all. Inspect the raw result of what `poll()` gives you back and you can probably see it, as long as your API protocol is set high enough  and your broker supports it. Otherwise if the api protocol is too low, then the broker will downgrade the record metadata and omit it.
