### ISSUE TITLE
Access kafka from outside not possible if kafka is behind traefik's ingress route

### ISSUE THREAD

**Issue by MarjanJordanovski** [dpkp/kafka-python#2311]
Hello,

This is more of a question:
Is it even possible to connect to kafka service (running in k8s cluster)  from outside of the k8s cluster, where kafka service is just simply exposed by ingress route (CRD resource for traefik proxy)?

For example, in my k8s cluster, IngressRoute is routing https://my-domain.com to kafka:9092 service. So in KafkaProducer or KafkaConsumer that are outside of the cluster, can I just use bootstrap_servers=[my-domain.com] ? Currently this gives me an error because if port is not specified, it automatically uses 9092, and then tries to contact my-domain.com:9092 which is not valid. (that's why NoBrokersAvailable error appears)

I tried setting bootstrap_servers=[my-domain.com:443] , (added 443 as a port to avoid using default 9092 port)  but then I get UnrecognizedBrokerVersion 

So without creating LB or exposing NodePort, is there a way to connect to kafka from outside the k8s cluster?

**Comment by sebosp** [comment]
Kafka has its own protocol, it's not HTTP. traefik/ingress-in-general try to load-balance connections, keep track of Endpoints, etc, which doesn't play well with kafka because kafka has a concept of broker-to-partition ownership (i.e. a partition is known to exist in _some_ brokers, _one_of them is owner of  a partition and only it will accept writes, and traefik is not aware (and should not be aware) of this ownership).
Each broker has an `advertised.listener` and there's a discovery mechanism, because partitions are hosted on different brokers, and the leadership is not completely static (i.e. broker goes down, another broker takes over).
One way you can make this work with kubernetes is:
- Create a headless service for each kafka-broker pod with different nodePort. For example, kafka-1 is nodePort 30992, kafka-2 is nodePort 30993, kafka-3 is nodePort 30994. This way you can talk to each kafka separately from outside kubernetes, this is required because you connect to kafka for a specific topic-partition and you are told which host:ip to talk to for writes on that partition (and reads almost always too).
- Each kafka pod configures the advertised listener to <external_ip_or_dns>:3099X, so kafka-1 has advertised listener <external_ip_or_dns>:30992, kafka-2 <external_ip_or_dns>:30993, ... This means that when I as a client outside kubernetes request the owners of a topic-partition, I am given an external IP addresses that I can resolve from outside kubernetes).
- You create an instance of a load-balancer that hosts such <external_Ip_or_dns> (i.e. AWS NLB) and that LB that forwards the traffic from :30992 to <k8s_workers_asg>:30992, from :30993 to <k8_workers_asg>:30993...
- From your external clients, you connect to the NLB as if it was the k8s cluster like:
`kafka-console-consumer.sh --broker-list <external_ip_or_dns>:9092,<external_ip_or_dns>:9093,<external_ip_or_dns>:9093` --list`.

**Comment by MarjanJordanovski** [comment]
Thanks! @sebosp
