### ISSUE TITLE
KafkaConsumer.task_done() interface - confusing?

### ISSUE THREAD

**Issue by Dinoshauer** [dpkp/kafka-python#292]
Given this example, the ``KafkaConsumer`` will commit the offset to kafka:

    import kafka

    consumer = kafka.KafkaConsumer(('test-topic-2', 5, ),
                                   group_id='my_consumer_group',
                                   metadata_broker_list=','.join(hosts),
                                   auto_commit_enable=True,
                                   auto_commit_interval_ms=1 * 1000,
                                   auto_offset_reset='smallest',)
    for msg in consumer:
        print(msg.offset)
        consumer.task_done(msg)

However with this configuration ``KafkaConsumer`` never commits any offsets. Is that intended behavior?

    consumer = kafka.KafkaConsumer(('test-topic-2', 5, ),
                                   group_id='my_consumer_group',
                                   metadata_broker_list=','.join(hosts),)

I would expect that calling ``#task_done()`` would always commit the offset from the message that was provided, and that enabling auto_commit with a time or message interval would commit by itself in the background like the ``SimpleConsumer`` does for example.

**Comment by wizzat** [comment]
I believe that's the desired behavior?

**Comment by wizzat** [comment]
@dpkp, comments?

**Comment by dpkp** [comment]
@Dinoshauer -- thanks for the feedback.  The original idea was to use `task_done` as an internal "ack" marker.  Those acks would then be committed to the server either on an `auto_commit` interval or on an explicit `commit()` call, but not immediately during the `task_done()` call.

But having worked with a handful of folks that are new to the API I have to agree that this setup seems confusing and is not what most people seem to expect.

Perhaps we should add a configuration parameter that controls the `task_done` behavior.  We could switch the default back to acking on read and not require you to call `task_done()`, making `auto_commit` "just work".  While we're at it, we might also change the name of `task_done` to `ack_message` or just `ack`.  And then I think we probably need to improve the documentation so that the relationship between commit, auto_commit, and task_done/ack are more clearly explained.

Thoughts?

**Comment by Dinoshauer** [comment]
I think you're on the right track @dpkp :) I think all of those changes sound very sensible.
Also, this may be unrelated (let me know if it is), but if I have messages from several different partitions, should I call ``task_done`` on each message with the highest offset pr. partition specifically?

**Comment by papisz** [comment]
+1, I got confused by task_done().
I thought that auto_commit "just works".

**Comment by dpkp** [comment]
The new KafkaConsumer drops support for manual 'acks' via task_done. Like the java client, messages are considered "consumed" as soon as they are delivered to the user from the client (either in batches via poll() / fetched_records() or one-by-one in an iterator)
