### ISSUE TITLE
Wrong report gave by produce() in Python Kafka Client when broker restarted

### ISSUE THREAD

**Issue by peichengcheng001** [dpkp/kafka-python#443]
I am working on Python [Kafka][1] client. When I restarted (ctrl-C to stop manually, and start again) the broker, **SOMETIMES** something wired happened. One message is sent to the broker, but it still thrown an exception (if sync_fail_on_error set to True, see the following). But I can see the message on the consumer. If sync_fail_on_error set to False, the return of **produce()** is list of object **FailedPayloadsError**. But the same message shown on the consumer.

                self.producer = Producer(
                    self.kafka_client,
                    async=False,
                    req_acks=Producer.ACK_AFTER_CLUSTER_COMMIT,
                    ack_timeout=2000,
                    sync_fail_on_error=True )

From the log file, I found that: sometimes the message was sent after the broker is up. Sometimes not. So we can not tell whether the message is sent to broker or not according to the response OR whether Exception is thrown or not.
Any suggestion is welcome... Thanks.

  [1]: http://kafka-python.readthedocs.org/en/latest/apidoc/kafka.html#module-kafka.client

**Comment by dpkp** [comment]
This seems consistent with a distributed system. It is possible for a remote server to write a message but fail before sending a response to the local client. In that case, the local client does not know that the message was successfully written and retries. In order to manage the possibility of messages being delivered more than once, I usually recommend that you include a unique message id in each and make sure your consumers are idempotent on multiple messages with the same unique id.

In any event, I recommend you use the new KafkaProducer that is in master.
