### ISSUE TITLE
difference b/w KafkaConsumer and SimpleConsumer

### ISSUE THREAD

**Issue by tanaysoni** [dpkp/kafka-python#453]
A detailed description could be added in the documentation.

**Comment by sebastianneubauer** [comment]
and in addition it is not quite helpful, that the api (constructor) is unnecessary different (group_id<>group). Maybe one could even drop the SimpleConsumer completely and absorb important parts missing in KafkaConsumer (e.g. reset_partition_offset) and add this simple usage in documentation, or just make a thin wrapper around KafkaConsumer with these simplifications and defaults...?

**Comment by sebastianneubauer** [comment]
ok, I just found out, that this SimpleConsumer is an API provided by kafka itself...maybe the name LowLevelConsumer, BasicConsumer or DoItYourselfConsumer would be a better choice from the kafka developers...currently my understanding is, the bad documentation and usability of kafka is leaking into this python client, am I right? Maybe it is not a good idea to fix this issue here, but it should be fixed in kafka?

**Comment by JasonGiedymin** [comment]
Unfortunately Kafka lingo shoukd translate and leak to the Api. Otherwise it would be hard to use this Api and more confusing let alone more work to wrap it to another domain of logic. Totally agree that the naming leaves much to be desired. But at least you can match semantics between this client and the raw Kafka APIs. Maybe when something like KafkaNew comes out we can these learnings and improve on the state of APIs so that they make more sense.

**Comment by dpkp** [comment]
My plan is to deprecate SimpleConsumer (and SimpleProducer) completely. The goal of KafkaConsumer is to use the same configuration parameters / lingo as the upstream Java client. Hopefully that will make tuning / discussion / debugging easier amongst the larger community.

I expect to start this process in a larger refactor for kafka 0.9 consumer group support.

**Comment by dpkp** [comment]
KafkaConsumer is updated to support 0.9.0.0 group coordination, and exposes the same api as the official java client. I do not recommend using SimpleConsumer and have removed the docs entirely. The code will likely be removed in a later release.
