### ISSUE TITLE
KafkaConsumer commit offset did not work

### ISSUE THREAD

**Issue by rockxsj** [dpkp/kafka-python#458]
```python
    def _handelData(self, topic, queue, partitions):
        self.consumer = KafkaConsumer(topic,
                           bootstrap_servers=self.kafkaBrokers,
                           group_id='iptvRockxsjaa',
                           auto_offset_reset='smallest',
                           auto_commit_enable=True,
                           auto_commit_interval_messages=100,
                           auto_commit_interval_ms=5 * 1000)
        i = 0
        for msg in self.consumer:
            if msg is None or len(msg.value) == 0:
                continue
            if not self._caseData(msg.value):
                continue
            i += 1
            if (i % 100) == 0:
                self.consumer.commit()
                print(msg.value)
                print(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())), msg.partition, msg.offset, i)
            self._putIntoRedis(queue, msg.value)
```

it is my code.
No matter I set auto_commit_enable or commit by call consumer.commit(), the result is common: When I kill the consumer,then restart it, it will consume message from the begining.

Is some thing wrong with my code?

**Comment by rockxsj** [comment]
If i did not set the auto_offset_reset param,It will consume message from the end of the topic.  How can I read from last commit offset?

**Comment by zoltan-fedor** [comment]
I had the same issue and then I realized when looking at my messages offsets, that while I consumed some messages they never got committed, so my offset was always Null when restarted the consumer, which resulted in Out of Range offset at all times, so the "auto_offset_reset" kicked in - which has the value 'latest' by default.

This means until you don't consume and commit message offset for the given group_id you will always seem to be starting from reading from the last record in the topic due to the default 'latest' value of the auto_offset_reset parameter.

Make sure that you consume something and get the message offset of those messages committed and then the next consumption will automatically start from the last offset (assuming your Zookeeper hasn't been reseted in the meantime).

**Comment by dpkp** [comment]
You need to ack each message to mark as ready for commit.

```
# **messages that are not marked w/ task_done currently do not commit!
consumer.task_done(m)
```

Let me know if that doesn't fix

**Comment by rockxsj** [comment]
thanks for reply!  I have fixed this by set param auto_offset_reset as default. The message is not important enough for me to make more try...       

At last,thanks again :)

**Comment by samjia533332** [comment]
@rockxsj  I am having the same problem, I do not know how to read from last message anytime the process is dropped or killed.

**Comment by rjurney** [comment]
I can't find task_done in KafkaConsumer's API :(

**Comment by kshamazingade** [comment]
@dpkp If there is a provision for auto committing offsets through the 'enable_auto_commit' parameter, why should we acknowledge the received message again. Also, when I try to use "task_done(message)", I am getting the error : **"'deprecated -- commit offsets manually if needed')
NotImplementedError: deprecated -- commit offsets manually if needed"** .

Many times, if my process using kafka consumer fails or is stopped purposely, I want to start reading from the last read message which is not possible with this glitch.
