### ISSUE TITLE
Help: kafka-python not receiving messages while one shard is down

### ISSUE THREAD

**Issue by ambientsound** [dpkp/kafka-python#596]
Hi,

It seems that kafka-python will stall incoming messages unless all replicated Kafka servers are operational and available. I can't find anything about this in the documentation.

To replicate:

- Set up one Zookeeper server
- Set up three Kafka servers and configure them to speak with the same Zookeeper endpoint
- Create a topic with 1 partition, and replication factor 3
- Start a kafka-python client and configure it to speak with all three Kafka servers:
```
import json, kafka
self.json_consumer = kafka.KafkaConsumer('mytopic',
                                         client_id='foobar',
                                         bootstrap_servers=[server1, server2, server3],
                                         enable_auto_commit=False,
                                         value_deserializer=lambda m: json.loads(m.decode('utf-8')))
```
- Send some messages to the topic. The client should be receiving the messages.
- Stop one of the Kafka servers.
- Send some messages to the topic. The client does not receive the messages. However, running the sample Kafka consumer shipped with the Kafka server shows that the messages are being committed: `kafka-console-consumer.sh --zookeeper x.x.x.x:2181/kafka --from-beginning --topic foo`
- Start the stopped Kafka server. The client receives all messages submitted during downtime.

**Comment by dpkp** [comment]
I can't reproduce this. Which version of kafka-python are you using? Can you dump the kafka-python logs for your consumer?

**Comment by akheron** [comment]
@ambientsound Did you wait long enough before deciding that the consumer doesn't get any messages and stopping it? Default `request_timeout_ms` for `KafkaConsumer` is 40000, so if a request to broker is interrupted, the consumer only notices this after 40 seconds in some situations. Lowering `request_timeout_ms` to e.g. 5000 should help.

@dpkp I just did some extensive testing in my environment and found out about all these timeouts and their effect by looking at debug-level consumer and producer logs. I think it would be helpful to document at some level how things work internally so that people get an idea of what parameters to tweak to get the desired result. At least in my case, tweaking `request_timeout_ms` and `retries` in the producer and `request_timeout_ms` in the consumer helped a lot.

**Comment by ambientsound** [comment]
It seems that my third Kafka server was configured against a non-existant Zookeeper instance. There was no error message when starting the server, and the process appeared to be running, thus I did not suspect that the server was configured incorrectly. Upon actually joining the three servers in the same cluster, the suspected bug disappeared. Thanks for your swift reply.
