### ISSUE TITLE
Question: How do I configure PROXY servers in my producer/consumer?

### ISSUE THREAD

**Issue by besenthil** [dpkp/kafka-python#680]
I want to configure PROXY settings for my producer and consumer. How do I set it up? Any help would be highly appreciated.

**Comment by dpkp** [comment]
What type of proxy? Generally kafka-python expects to connect directly to
your Kafka brokers.

**Comment by besenthil** [comment]
its a firewall proxy.

**Comment by dpkp** [comment]
I don't believe this is possible unless your brokers are configured with the firewall proxy as the advertised host. In any event, this is a kafka broker configuration issue, not related to kafka-python. You should check on the kafka users mailing list for configuration tips for brokers connected to via proxy.

**Comment by Sabotaz** [comment]
Hello,
I actually have a usecase where my kafka broker is not publicly available and is behind a VPN, who is mounted on a router, and the applications need to speak with the router through a squid proxy.
The java consumers and producers are able to connect because this proxy is configured on the JVM side (using a ProxySelector) and is used for all TCP connections.
So i would like to do the same and proxy the kafka connection through this same route as well. Technically it should be doable :(
