### ISSUE TITLE
Help: Commit can't be completed since group has already rebalanced...

### ISSUE THREAD

**Issue by nursejason** [dpkp/kafka-python#746]
Made the switch from `pykafka` to `kafka-python` over the weekend, which resolved an issue where my `Producer` would hang sending data to a Kafka cluster I don't control. 

This has had the unforeseen consequence of not allowing me to commit my offsets, seemingly only for messages that take a while to process (but I've seen some other messages processed that may be duplicates), though that could be an incorrect assumption. I've never noticed problems updating my offset with the other library, and thus I don't think it has anything to do with Kafka broker settings, likely just something with my consumer.

For reference, I'm using Kafka-Python 1.2.2 and Kafka 0.9
```
Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

I'm simply creating a single consumer with a group, grabbing the first message available, processing it, and moving on. 
```Python
consumer = KafkaConsumer(topic, bootstrap_servers=server_list, group_id=group, enable_auto_commit=False)
for message in consumer:
     process_message(message.value)
     consumer.commit()
```

**Comment by dpkp** [comment]
How long does your `process_message` take in the worst case? Are you using the default heartbeat and session timeout parameters (it appears so from the consumer side, but you might verify that you haven't modified default server-side configs).

pykafka maintains a custom leader election / partition assignment system, and I don't know the details well enough to comment on it. kafka-python attempts to implement exactly the same group coordination system, algorithms, and configuration parameters as the official java client. But you have found one of the issues with the official implementation, namely that "long" message processing can cause unwanted group rebalance operations and interfere with offset commits etc. Rather than implement and maintain our own system here, I prefer to follow the official implementation. They are currently discussing / implementing a background heartbeat mechanism that should help address. Until then, the recommendation is to tune your heartbeat and session timeouts relative to your worst case message processing time.

**Comment by nursejason** [comment]
Worst case is `> 30 seconds`, which makes it seem like it's hitting the `session_timeout_ms`. Though I don't know why pykafka wouldn't have complained or errored in that case. Or the alternative, that it was silently failing and repeating the same messages ad nauseum. Unfortunately I haven't been able to figure out the correct setting in Kafka to update in order to allow the increase of `session_timeout_ms`.

**Comment by dpkp** [comment]
pykafka wrote their own group management protocol with their own design for failover, heartbeats, etc. I dont think you can draw any parallels to the official design / group management apis in 0.9.

**Comment by nursejason** [comment]
Fair enough! I'll withdraw my relation ;)

**Comment by dpkp** [comment]
`group.max.session.timeout.ms` is the broker configuration. It defaults to 30000 (30 seconds). If you increase that you should be able to pass a larger value for `session_timeout_ms` to your KafkaConsumer instances.

**Comment by nursejason** [comment]
I had updated that value last night in my testing, but didn't notice a change when I restarted my broker. Checked this morning and the config hadn't persisted through the reboot. I use Ambari to manage Kafka, and it must have overwritten my manual config update. Made a guess on where to insert it in Ambari (`custom kafka broker` section), did a rolling restart, and now I see the `group.max.session.timeout.ms` var in the `server.properties` file. 

Now all is well!

Out of curiosity, if for whatever reason, my new max session timeout is exceeded and I can't commit the offset, how do I prevent consuming the message over and over?

**Comment by dpkp** [comment]
I don't think there is a good solution apart from increasing session
timeout or decreasing msg processing time. You might check the Kafka users
mailing list to see if others have found different ways to manage.

**Comment by nursejason** [comment]
Fair enough! Then I'm happy to close this if you are!

**Comment by dpkp** [comment]
No problem!

**Comment by wenjiezhang2013** [comment]
Is there a way that I can send the heartbeat to the server asynchronously while I am processing the message on the consumer side?

**Comment by jeffwidman** [comment]
@wenjiezhang2013 you're probably looking for https://github.com/dpkp/kafka-python/issues/948

FYI: rather than commenting on an old issue, it's generally better to start a new one. Too easy for your comment to get lost. And in the case of questions, many open source projects prefer that questions go on StackOverflow and reserve the issue tracker for bug reports/feature requests. Not sure what @dpkp prefers.

**Comment by iranpak** [comment]
Hi
i use camel component of kafka and i set `max.poll.interval.ms` to 10000 and then will delay about 25 seconds in my process and route and expect to see rebalancing the group id and failure of commiting the message, but nothing happens and message is successfully commited!
am i doing something wrong?
any opinion about this?

**Comment by meedeepak** [comment]
Try setting `legacy_iterator=True` in `KafkaConsumer` or use `poll()` because somehow `next_v2` does't seems to work on of the class
