### ISSUE TITLE
Producers don't fail over when a broker crashes abruptly

### ISSUE THREAD

**Issue by kishorenc** [dpkp/kafka-python#847]
We're pushing about 1,000 events per second to Kafka from a cluster of 50+ servers. When a kafka broker is terminated abruptly, about 10% of the clients do not seem to fail over to the backup node to continue the writes. The throughput drops to about 900 events per second, and we see a lot of `KafkaTimeoutError` errors. We're on version `1.3.1` and are using the sync interface like this:

``` python
try:
    future = self.kafka_producer.send(topic, message)
    future.get(timeout=0.5)
except KafkaError as e:
    raise e        
```

Here are the other non-default client settings we use:

```
metadata_max_age_ms = 20000
request_timeout_ms = 500
reconnect_backoff_ms = 1000
```

These clients do not recover even after 10 minutes. If I did a graceful shutdown of the Kafka broker, 
there is absolutely no issue - failover happens promptly without any disruption. I ran this experiment multiple times over multiple days to verify.

**Comment by dpkp** [comment]
This seems normal to me. When a leader goes down you should expect failed sends unless you are configuring `retries` . Note that not *all* sends will fail, but any that were in-flight will probably fail. You should also expect some delay caused by the metadata refresh cycle whenever a node goes down. `KafkaTimeoutError` is raised specifically when the result of your future is not ready yet. So in this case you want a response in 500 ms and it isn't ready yet, so you get a timeout error. Have you tried increasing the timeout in `future.get(timeout=0.5)` ?

Also, if you `raise e` aren't you crashing your producer ? I don't think you can expect any python client to recover if you raise an unhandled exception ;)

**Comment by kishorenc** [comment]
@dpkp: 

Sorry, the `raise e` was being caught by the calling function and was also doing a retry on catching the exception (code snippet below). On further investigation, I noticed the following behavior: 

When one of the Kafka nodes is shut down gracefully, everything is great and no events are dropped. However, if the kafka process is killed with a `-9`, 90% of the clients are able to failover but 10% of the clients do not failover at all. They continue to try and write to the old node and keep failing with connection timeouts.

I can understand that some sends will fail during the fail-over during the metadata refresh cycle, but I can see from the logs that some 10% of the clients don't failover to the backup node well after 20-30 minutes (I stopped at that point). 

```python
def send_with_retry(self, topic, value):
    attempts = 1 + settings.EVENTS_KAFKA_NUM_RETRIES
    while attempts > 0:
        try:            
            self.push_event_to_kafka(topic, value)
            attempts = 0
        except Exception:
            attempts -= 1
            # We've exhausted all attempts without succeeding
            if attempts == 0:
                self.log_kafka_error(topic, value)    
```

**Comment by dpkp** [comment]
Does this still happen? This sounds to me like it may have been related to #887 which was fixed in 1.3.2

**Comment by jeffwidman** [comment]
bump @kishorenc

**Comment by kishorenc** [comment]
I haven't had a chance to retest. The errors occurred only under a significant load and it requires an elaborate set-up to reproduce. We've since gone to production. I'm going to close this issue for now.
