### ISSUE TITLE
Deactivate auto reconnect for consumer

### ISSUE THREAD

**Issue by patrickviet** [dpkp/kafka-python#861]
Here is the problem

Sample code: use the next iterator, and go through.
I handle my own timeouts, retries, what I do, when I commit (one message at a time), what I log, etc.

``` python
from kafka import KafkaConsumer
consumer = KafkaConsumer('mytopic', boostrap_servers='myserver', consumer_timeout_ms=1000, enable_auto_commit=False)

while True:
  try:
    print "start iteration"
    data = next(consumer)
    # do some processing, and if it went well, commit
    consumer.commit()
  except StopIteration:
    print "cycle back"

```

For normal processing, when kafka is running fine, it will print start interation, cycle back every second if I don't have any new messages in my kafka topic, except that if I stop kafka, it will block at the next(consumer) forever. And then if I restart kafka, it will reconnect and do as if nothing had gone wrong.

How can I stop the "magic" behavior? I'd like it to just throw an exception if it disconnects, and let me do the reconnect on my own terms.

**Comment by patrickviet** [comment]
This is a huge blocker since it means no debug in case of problem - where in the code is this happening? How can I have the next(consumer) not block for over one second?

**Comment by dpkp** [comment]
Unfortunately, as I understand it, this is an issue in both the official client and kafka-python. If the cluster is completely down, the client attempts to refresh metadata indefinitely in a blocking loop. Specifically `KafkaClient._maybe_refresh_metadata` calls `least_loaded_node` which will fallback to `_bootstrap` and block if the cluster is down.

**Comment by felipou** [comment]
The biggest problem for me is that this doesn't let us control error detection and logging.

Also, to detect long disconnections, we had to start checking the timestamp of received messages to see if they are too old, and prepare the application for that case. If we could detect connection timeouts or errors, we could prepare in those cases instead of checking every message.

I believe this issue is somewhat related to https://github.com/dpkp/kafka-python/issues/1043

**Comment by dpkp** [comment]
I'm not clear on what exactly is requested here. Is there an error that you feel is not handled well now? If so, how would you prefer that it be handled instead?

"detecting disconnections" is currently handled within the cluster logic. When a broker fails, and the cluster reassigns the partitions to a different broker that is working, the client will seemlessly switch to the new leader and continue consuming.

**Comment by patrickviet** [comment]
If it doesn't manage to connect/reconnect to anything after X seconds - I'd like an exception

**Comment by felipou** [comment]
Or an error event. If the client can't connect to any broker at all, I'd like to know that. Perhaps there is a network issue on something, and I'd like to issue a warning so that someone can take action, or maybe just be aware that the client isn't able to connect and possibly delayed.

**Comment by felipou** [comment]
By the way, I'm more than willing to help achieve that. I can try creating a PR if you can give me some pointers (which classes to modify, what design changes would have to be considered and so forth).

**Comment by jeffwidman** [comment]
> I'd like for this to exist as well, in containerized environments like kubernetes, if the cluster goes down and comes back up, the brokers will get different IPs, and the client will keep trying to refresh metadata from nonexistent brokers forever, with a timeout or a number of maximum retries, the client would die and kubernetes would fire it again.

Although unrelated to the original issue, that is a definite bug, we shouldn't cache those IP's forever. However, IIRC since this issue was last updated there have been a number of fixes to DNS resolution that have been merged.

I'm going to close this. If you can replicate this issue with the `2.x` series, please open a new ticket and lets get it fixed.
