### ISSUE TITLE
Use Kafka Fetch Request Version 3

### ISSUE THREAD

**Issue by Drizzt1991** [dpkp/kafka-python#870]
Hi, as I can see there's still no support for Version 3 of Fetch requests (with an max_bytes for all partitions, see https://kafka.apache.org/protocol).

**Comment by Drizzt1991** [comment]
It was introduced in Kafka 0.10.1.0, is anyone currently working on adding this? If not I think, I can add it myself. It shouldn't be too hard, with the exception, that topics will now be order-sensitive.

**Comment by dpkp** [comment]
I have not started working on this. PR welcome!

**Comment by jeffwidman** [comment]
Added the struct itself in #943 because I had a little extra time... not sure I'll be able to finish this, anyone else feel free to continue...

Still to do before closing this issue:
- [ ]  add `(0, 10, 1)` to the list of supported `api_version`s
- [ ]  verify the logic of `api_version` checking still works... not sure how it handles a three part tuple vs two part.
- [ ]  do we need to shuffle the topics on request? @Drizzt1991 mentioned this, but I'm not sure where/how to implement.
- [ ]  actually pass in a value for the new `max_bytes` field

**Comment by Drizzt1991** [comment]
Hmm, as I opened the ticket it will take it. I do have time this evening. Thanks for the start.

**Comment by Drizzt1991** [comment]
Emm, it was closed and released in 1.3.3 :) closing
