### ISSUE TITLE
Consumer does not fetch from beginning

### ISSUE THREAD

**Issue by chengyu-liu-cs** [dpkp/kafka-python#983]
Hi,

I encountered an issue. Consumer does not return all data related to a topic even if I used auto_offset_reset='earliest' parameter.

I saw there was similar issue open before but not closed https://github.com/dpkp/kafka-python/issues/691. 

Following is my simple test code. It returned 8 entries. But there are 14 entries. If I use bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --from-beginning --topic test-topic command it shows there are 14.

Another issue was that this script returns nothing if I run this script after killing it.

Can someone help ?

kafka_server = 'localhost:9092'
topics = ('test-topic')
consumer = KafkaConsumer(topics, bootstrap_servers=kafka_server, auto_offset_reset='earliest')
for message in consumer:
    bytes_reader = io.BytesIO(message.value)
    print(type(bytes_reader))
consumer.close()

## return 8 entries
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>
<type '_io.BytesIO'>

**Comment by jeffwidman** [comment]
Did you reset the cluster beforehand? 

`auto_offset_reset` only kicks in if there are no offsets stored... as soon as you run the consumer once, it will by default auto-commit an offset. This offset will be used on the next run unless the offset is removed either by resetting the cluster or the offset expiring from the internal offsets topic.

**Comment by chengyu-liu-cs** [comment]
I have not done any reset. I thought this offset for a topic will be stored forever and auto_offset_reset is used to reset the offset. If this is not meant to reset, can you explain more about how to reset and how to set offset retention for a topic ?

**Comment by jeffwidman** [comment]
Your best bet is probably StackOverflow as those are generic Kafka questions, not specific to `kafka-python`.

**Comment by chengyu-liu-cs** [comment]
Alright. Thanks @jeffwidman

**Comment by farscape2012** [comment]
One thing I find is following. It seems that auto_offset_reset can be used to fetch earlier data. I am not sure whether @jeffwidman said is correct.

Why does my consumer never get any data? (fromhttps://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Consumers )
By default, when a consumer is started for the very first time, it ignores all existing data in a topic and will only consume new data coming in after the consumer is started. If this is the case, try sending some more data after the consumer is started. Alternatively, you can configure the consumer by setting auto.offset.reset to "earliest" for the new consumer in 0.9 and "smallest" for the old consumer.

**Comment by dpkp** [comment]
No, Jeff is correct. But one key difference is that the Java client forces
you to manually pick a group id, while kafka-python supplies a default
(kafka-python-default). So Java docs assume that your "new" consumer also
has a new group id.

You can disable all group functionality by setting group_id=None .

On Feb 10, 2017 2:17 AM, "farscape2012" <notifications@github.com> wrote:

One thing I find is following. It seems that auto_offset_reset can be used
to fetch earlier data. I am not sure whether @jeffwidman
<https://github.com/jeffwidman> said is correct.

Why does my consumer never get any data? (fromhttps://cwiki.apache.org/
confluence/display/KAFKA/FAQ#FAQ-Consumers )
By default, when a consumer is started for the very first time, it ignores
all existing data in a topic and will only consume new data coming in after
the consumer is started. If this is the case, try sending some more data
after the consumer is started. Alternatively, you can configure the
consumer by setting auto.offset.reset to "earliest" for the new consumer in
0.9 and "smallest" for the old consumer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dpkp/kafka-python/issues/983#issuecomment-278907370>,
or mute the thread
